#pragma once
#define VNU_ABI_VERSION 1

#define VNU_SYS_read      0
#define VNU_SYS_write     1
#define VNU_SYS_open      2
#define VNU_SYS_close     3
#define VNU_SYS_exit      4
#define VNU_SYS_lseek     5
#define VNU_SYS_stat      6
#define VNU_SYS_fstat     7
#define VNU_SYS_brk       8
#define VNU_SYS_getpid    9
#define VNU_SYS_chdir    10
#define VNU_SYS_getcwd   11
#define VNU_SYS_fork     12
#define VNU_SYS_execve   13
#define VNU_SYS_getuid   14
#define VNU_SYS_getgid   15
#define VNU_SYS_mkdir    16
#define VNU_SYS_rmdir    17
#define VNU_SYS_unlink   18
#define VNU_SYS_getdents 19
#define VNU_SYS_waitpid  20
#define VNU_SYS_pipe     21
#define VNU_SYS_dup      22
#define VNU_SYS_dup2     23
#define VNU_SYS_kill     24
#define VNU_SYS_uname    25
#define VNU_SYS_getppid  26
#define VNU_SYS_isatty   27
#define VNU_SYS_spawn    28
#define VNU_SYS_blkcount 29
#define VNU_SYS_install  30
#define VNU_SYS_setuid   31
#define VNU_SYS_setgid   32
#define VNU_SYS_chmod    33
#define VNU_SYS_chown    34
#define VNU_SYS_reboot   35
#define VNU_SYS_time     36
#define VNU_SYS_uptime   37
#define VNU_SYS_ping     38
#define VNU_SYS_netinfo  39

#define VNU_EPERM 1
#define VNU_ENOENT 2
#define VNU_ESRCH 3
#define VNU_EIO 5
#define VNU_ENOEXEC 8
#define VNU_EBADF 9
#define VNU_ECHILD 10
#define VNU_EAGAIN 11
#define VNU_ENOMEM 12
#define VNU_EACCES 13
#define VNU_EFAULT 14
#define VNU_EBUSY 16
#define VNU_EEXIST 17
#define VNU_ENOTDIR 20
#define VNU_EISDIR 21
#define VNU_EINVAL 22
#define VNU_ENOSPC 28
#define VNU_ERANGE 34
#define VNU_ETIMEDOUT 110
#define VNU_EHOSTUNREACH 113
#define VNU_ENOSYS 38
#define VNU_ENOTEMPTY 39
#define VNU_EPIPE 32

#define VNU_ESRCH 3
