#!/bin/sh
# Bash trampoline: /usr/bin/env is missing on some hosts (e.g. Termux
# without termux-exec) -- if not under bash already, re-exec via PATH.
if [ -z "${BASH_VERSION:-}" ]; then exec env bash "$0" "$@"; fi
# Generate the GRUB stage blobs that the in-system installer writes to a
# target disk. Produces, in $1:
#   vnu_install_blobs.inc   a NASM include carrying the embedded symbols and
#                           incbin lines for boot.img/core.img
# as well as regenerating boot.img (drive byte pinned to 0x80) and
# core.img (GRUB core image with a tiny embedded config that finds the
# VNU volume by label).
#
# With --stub (no grub-mkimage on the host, e.g. Termux) it emits
# zero-length arrays instead: the kernel still links and boots, only the
# `install` disk-writer payload is empty.
set -euo pipefail

STUB=0
if [[ "${1:-}" == "--stub" ]]; then
    STUB=1
    OUT="${2:?usage: gen_install_blobs.sh [--stub] OUTDIR [GRUBDIR]}"
else
    OUT="${1:?usage: gen_install_blobs.sh [--stub] OUTDIR [GRUBDIR]}"
fi
GRUBDIR="${2:-/usr/lib/grub/i386-pc}"

mkdir -p "$OUT"

if [[ $STUB -eq 1 ]]; then
    cat > "$OUT/vnu_install_blobs.inc" <<'INC'
; generated by gen_install_blobs.sh --stub (grub-mkimage unavailable)
section .rodata
align 4
global vnu_install_boot_img
global vnu_install_boot_img_end
vnu_install_boot_img:
vnu_install_boot_img_end:
align 4
global vnu_install_core_img
global vnu_install_core_img_end
vnu_install_core_img:
vnu_install_core_img_end:
INC
    echo "install blobs: stub (no grub-mkimage)"
    exit 0
fi

if [[ ! -f "$GRUBDIR/boot.img" ]]; then
    echo "gen_install_blobs: $GRUBDIR/boot.img not found" >&2
    exit 1
fi

# GRUB's boot.img hard-codes the BIOS boot drive at offset 0x64; force it
# to 0x80 so the installed first stage always talks to the first hard disk.
python3 - "$GRUBDIR/boot.img" "$OUT/boot.img" <<'PY'
import sys
src, dst = sys.argv[1:3]
b = bytearray(open(src, 'rb').read())
if len(b) > 0x65:
    b[0x64] = 0x80
open(dst, 'wb').write(b)
PY

# core.img: embedded early config finds the VNU volume by label and hands
# off to /boot/grub/grub.cfg on that volume.
BOOTCFG="$OUT/install_boot.cfg"
cat > "$BOOTCFG" <<'CFG'
search --label VNU --set=root
set prefix=($root)/boot/grub
configfile ($root)/boot/grub/grub.cfg
CFG
grub-mkimage -O i386-pc -o "$OUT/core.img" -p /boot/grub -c "$BOOTCFG" \
    biosdisk part_msdos fat normal multiboot2 search search_label

python3 - "$OUT" <<'PY'
import sys, os
out = sys.argv[1]
sz = lambda n: os.path.getsize(os.path.join(out, n))
inc = f"{out}/vnu_install_blobs.inc"
with open(inc, 'w') as f:
    f.write("; generated by gen_install_blobs.sh (do not edit)\n")
    f.write("section .rodata\n")
    f.write("align 4\n")
    f.write("global vnu_install_boot_img\n")
    f.write("global vnu_install_boot_img_end\n")
    f.write("vnu_install_boot_img:\n")
    f.write('    incbin "%s/boot.img"\n' % out)
    f.write("vnu_install_boot_img_end:\n")
    f.write("align 4\n")
    f.write("global vnu_install_core_img\n")
    f.write("global vnu_install_core_img_end\n")
    f.write("vnu_install_core_img:\n")
    f.write('    incbin "%s/core.img"\n' % out)
    f.write("vnu_install_core_img_end:\n")
print("boot.img", sz('boot.img'), "core.img", sz('core.img'))
PY
