#!/bin/sh
# Bash trampoline: /usr/bin/env is missing on some hosts (e.g. Termux
# without termux-exec) -- if not under bash already, re-exec via PATH.
if [ -z "${BASH_VERSION:-}" ]; then exec env bash "$0" "$@"; fi
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$ROOT_DIR/kernel/build"
SOURCE_DIR="$ROOT_DIR/kernel"
SEED_DIR="$ROOT_DIR/grub-seed"

# CMake stores absolute source/build paths in CMakeCache.txt. A build
# directory copied from another machine/archive must be reconfigured.
if [[ -f "$BUILD_DIR/CMakeCache.txt" ]]; then
    cached_home="$(sed -n 's|^CMAKE_HOME_DIRECTORY:INTERNAL=||p' "$BUILD_DIR/CMakeCache.txt" | head -n1 || true)"
    if [[ -n "$cached_home" && "$cached_home" != "$SOURCE_DIR" ]]; then
        echo "CMake cache belongs to: $cached_home"
        echo "Current source tree is: $SOURCE_DIR"
        echo "Removing stale build cache..."
        rm -rf "$BUILD_DIR"
    fi
fi

cmake -S "$SOURCE_DIR" -B "$BUILD_DIR"
cmake --build "$BUILD_DIR" -j"$(nproc 2>/dev/null || echo 1)"

# Stage the ISO payload: kernel, grub.cfg and (for the portable path) the
# GRUB El Torito boot image + modules, so the staging dir mirrors what
# grub-mkrescue would produce.
mkdir -p "$ROOT_DIR/iso/boot/grub"
cp "$BUILD_DIR/kernel.elf" "$ROOT_DIR/iso/boot/kernel.elf"

cat > "$ROOT_DIR/iso/boot/grub/grub.cfg" <<'EOF'
set timeout=0
set default=0
menuentry "VNU" {
    multiboot2 /boot/kernel.elf
    module2 /boot/kernel.elf
    boot
}
EOF

# GRUB stage files for the ISO boot image come from the SEED_DIR: a copy of
# /boot/grub/i386-pc + /efi.img from a grub-mkrescue-produced ISO (they are
# spec-agnostic bootloader blobs, not build output of this tree). The seed
# is (re)generated by pulling those files out of an existing vnu.iso; a
# machine that has grub-mkrescue never needs the seed at all.
ensure_grub_seed() {
    if [[ -f "$SEED_DIR/i386-pc/eltorito.img" && -f "$SEED_DIR/efi.img" ]]; then
        return 0
    fi
    if [[ ! -f "$ROOT_DIR/vnu.iso" ]]; then
        echo "Нет grub-mkrescue и нет vnu.iso, из которого можно извлечь GRUB-ready" >&2
        echo "загрузочные файлы (eltorito.img + модули + efi.img)." >&2
        echo "Варианты: собрать ISO один раз на машине с grub-mkrescue," >&2
        echo "или положить готовый vnu.iso рядом с этим скриптом." >&2
        exit 1
    fi
    echo "Извлекаю GRUB-блобы загрузки из vnu.iso -> $SEED_DIR ..."
    rm -rf "$SEED_DIR"
    mkdir -p "$SEED_DIR"
    xorriso -osirrox on -indev "$ROOT_DIR/vnu.iso" \
        -extract /boot/grub/i386-pc "$SEED_DIR/i386-pc" >/dev/null
    xorriso -osirrox on -indev "$ROOT_DIR/vnu.iso" \
        -extract /efi.img "$SEED_DIR/efi.img" >/dev/null
    chmod -R u+rwX "$SEED_DIR"
}

# Portable ISO builder: reproduces what grub-mkrescue does with xorriso,
# using the pre-built GRUB blobs from the seed. Used on hosts where the
# grub tools are not installed (e.g. Termux).
build_iso_portable() {
    ensure_grub_seed

    chmod -R u+rwX "$ROOT_DIR/iso" 2>/dev/null || true
    rm -rf "$ROOT_DIR/iso/boot/grub/i386-pc" "$ROOT_DIR/iso/efi.img"
    cp -a "$SEED_DIR/i386-pc" "$ROOT_DIR/iso/boot/grub/i386-pc"
    cp -a "$SEED_DIR/efi.img" "$ROOT_DIR/iso/efi.img"

    xorriso -as mkisofs \
        -V ISOIMAGE \
        -b boot/grub/i386-pc/eltorito.img \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        --grub2-boot-info \
        -eltorito-alt-boot \
        -e efi.img \
        -no-emul-boot \
        -boot-load-size 5760 \
        -o "$ROOT_DIR/vnu.iso" "$ROOT_DIR/iso"
}

if command -v grub-mkrescue >/dev/null 2>&1; then
    grub-mkrescue -o "$ROOT_DIR/vnu.iso" "$ROOT_DIR/iso"
else
    build_iso_portable
fi
echo "Готово: $ROOT_DIR/vnu.iso"
